name: shlink
description: A Library to manage shlink.io based self-hosted URL shortener.
version: 0.6.0
homepage: https://github.com/Nexific/dart_shlink

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
